language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild -project KeyboardHelper.xcodeproj -scheme KeyboardHelper -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S' build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)

